title: My Portfolio
description: A collection of my work as a Shopify Developer
url: "https://www.flourishengineering.com"
baseurl: ""
permalink: /:year/:month/:day/:title/ # URL structure for posts

markdown: kramdown # Defines markdown processor
